version: '2.3'
services:
  elasticsearch:
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "ELASTIC_PASSWORD=changeme"
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.5.0-SNAPSHOT"
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ${SERVICE_LOGS_DIR}:/usr/share/elasticsearch/logs
    ports:
      - "127.0.0.1:9201:9200"
